-- Migrazione 032 — Motore riconciliazione v2 (single source bank_transactions + payables)
-- Algoritmo a 3 assi: importo (50pt), nome/VAT supplier (30pt), data scadenza (20pt)
-- Soglie: >=80 auto_exact (applica), 50-79 auto_fuzzy (suggerito), <50 nessun match

CREATE TABLE IF NOT EXISTS public.reconciliation_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL,
  bank_transaction_id UUID REFERENCES public.bank_transactions(id) ON DELETE CASCADE,
  payable_id UUID REFERENCES public.payables(id) ON DELETE SET NULL,
  match_type TEXT NOT NULL CHECK (match_type IN ('auto_exact', 'auto_fuzzy', 'manual', 'rejected')),
  confidence NUMERIC(5, 2) NOT NULL,
  score_amount NUMERIC(5, 2),
  score_name NUMERIC(5, 2),
  score_date NUMERIC(5, 2),
  status TEXT NOT NULL DEFAULT 'applied' CHECK (status IN ('applied', 'to_confirm', 'rejected')),
  notes TEXT,
  performed_by UUID,
  performed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  confirmed_at TIMESTAMPTZ
);

CREATE INDEX idx_reclog_bt ON public.reconciliation_log(bank_transaction_id);
CREATE INDEX idx_reclog_payable ON public.reconciliation_log(payable_id);
CREATE INDEX idx_reclog_status ON public.reconciliation_log(status, performed_at DESC);

ALTER TABLE public.reconciliation_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY reclog_read_authenticated ON public.reconciliation_log FOR SELECT TO authenticated USING (true);
CREATE POLICY reclog_service_write ON public.reconciliation_log FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY reclog_authenticated_write ON public.reconciliation_log FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY reclog_authenticated_update ON public.reconciliation_log FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Function: prova match di una bank_transaction contro tutte le payable da_pagare
CREATE OR REPLACE FUNCTION public.try_match_bank_transaction(p_bt_id UUID)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_bt RECORD;
  v_pay RECORD;
  v_best_payable_id UUID;
  v_best_score NUMERIC := 0;
  v_best_amount NUMERIC := 0;
  v_best_name NUMERIC := 0;
  v_best_date NUMERIC := 0;
  v_score_amount NUMERIC;
  v_score_name NUMERIC;
  v_score_date NUMERIC;
  v_score_total NUMERIC;
  v_amount_diff_pct NUMERIC;
  v_days_diff INTEGER;
  v_match_type TEXT;
  v_log_status TEXT;
  v_descr TEXT;
BEGIN
  SELECT * INTO v_bt FROM public.bank_transactions WHERE id = p_bt_id;
  IF v_bt IS NULL OR v_bt.amount >= 0 THEN
    RETURN jsonb_build_object('skipped', true, 'reason', 'amount_not_negative_or_tx_not_found');
  END IF;

  v_descr := lower(coalesce(v_bt.description, '') || ' ' || coalesce(v_bt.counterpart, '') || ' ' || coalesce(v_bt.merchant_name, ''));

  FOR v_pay IN
    SELECT * FROM public.payables
    WHERE company_id = v_bt.company_id
      AND status IN ('da_pagare', 'in_scadenza', 'scaduto')
      AND bank_transaction_id IS NULL
      AND gross_amount > 0
  LOOP
    -- Asse importo (50pt)
    v_amount_diff_pct := abs(abs(v_bt.amount) - v_pay.gross_amount) / v_pay.gross_amount * 100;
    v_score_amount := GREATEST(0, 50 - v_amount_diff_pct * 5);

    -- Asse nome (30pt): VAT esatto / supplier_name presente / similarity
    v_score_name := 0;
    IF v_pay.supplier_vat IS NOT NULL AND v_descr LIKE '%' || lower(v_pay.supplier_vat) || '%' THEN
      v_score_name := 30;
    ELSIF v_pay.supplier_name IS NOT NULL AND v_descr LIKE '%' || lower(v_pay.supplier_name) || '%' THEN
      v_score_name := 25;
    ELSIF v_pay.supplier_name IS NOT NULL THEN
      v_score_name := similarity(v_descr, lower(v_pay.supplier_name)) * 30;
    END IF;

    -- Asse data (20pt): 1pt per giorno di differenza fino a 20gg
    v_days_diff := abs(v_bt.transaction_date - v_pay.due_date);
    v_score_date := GREATEST(0, 20 - v_days_diff);

    v_score_total := v_score_amount + v_score_name + v_score_date;

    IF v_score_total > v_best_score THEN
      v_best_score := v_score_total;
      v_best_payable_id := v_pay.id;
      v_best_amount := v_score_amount;
      v_best_name := v_score_name;
      v_best_date := v_score_date;
    END IF;
  END LOOP;

  IF v_best_payable_id IS NULL OR v_best_score < 50 THEN
    RETURN jsonb_build_object('matched', false, 'best_score', v_best_score);
  END IF;

  IF v_best_score >= 80 THEN
    v_match_type := 'auto_exact';
    v_log_status := 'applied';
  ELSE
    v_match_type := 'auto_fuzzy';
    v_log_status := 'to_confirm';
  END IF;

  INSERT INTO public.reconciliation_log (
    company_id, bank_transaction_id, payable_id, match_type, confidence,
    score_amount, score_name, score_date, status, notes
  ) VALUES (
    v_bt.company_id, p_bt_id, v_best_payable_id, v_match_type, v_best_score,
    v_best_amount, v_best_name, v_best_date, v_log_status,
    'auto-generated by try_match_bank_transaction'
  );

  IF v_match_type = 'auto_exact' THEN
    UPDATE public.payables
    SET bank_transaction_id = p_bt_id,
        status = 'pagato'::payable_status,
        amount_paid = gross_amount,
        amount_remaining = 0,
        payment_date = v_bt.transaction_date,
        updated_at = now()
    WHERE id = v_best_payable_id;
  END IF;

  RETURN jsonb_build_object(
    'matched', true,
    'payable_id', v_best_payable_id,
    'score', v_best_score,
    'match_type', v_match_type,
    'applied', v_match_type = 'auto_exact'
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.try_match_bank_transaction(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.try_match_bank_transaction(UUID) TO authenticated, service_role;

-- Trigger DB sincrono: al INSERT bank_transactions, prova match
CREATE OR REPLACE FUNCTION public.trg_auto_reconcile_bank_transaction()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.status = 'posted' AND NEW.amount < 0 THEN
    PERFORM public.try_match_bank_transaction(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_auto_reconcile_on_bank_tx ON public.bank_transactions;
CREATE TRIGGER trg_auto_reconcile_on_bank_tx
  AFTER INSERT ON public.bank_transactions
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_auto_reconcile_bank_transaction();

-- RPC manuale per ri-tentare match su tutto
CREATE OR REPLACE FUNCTION public.rerun_reconciliation()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  r RECORD;
  v_processed INT := 0;
  v_matched INT := 0;
  v_result jsonb;
BEGIN
  FOR r IN
    SELECT id FROM public.bank_transactions
    WHERE amount < 0 AND status = 'posted'
      AND id NOT IN (SELECT bank_transaction_id FROM public.reconciliation_log WHERE bank_transaction_id IS NOT NULL)
  LOOP
    v_processed := v_processed + 1;
    v_result := public.try_match_bank_transaction(r.id);
    IF (v_result->>'matched')::boolean THEN
      v_matched := v_matched + 1;
    END IF;
  END LOOP;

  RETURN jsonb_build_object('processed', v_processed, 'matched', v_matched);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.rerun_reconciliation() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rerun_reconciliation() TO authenticated, service_role;
